#!/usr/bin/env bash

# environment variables
if [[ -z $STOW_FOLDERS ]]; then
	STOW_FOLDERS=("iterm" "nvim" "tmux" "karabiner" "ideavim" "zsh" "git" "gpg")
fi

if [[ -z $DOTFILES ]]; then
	DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS
DOTFILES=$DOTFILES
