#!/usr/bin/env bash

# environment variables
if [[ -z $STOW_FOLDERS ]]; then
	STOW_FOLDERS=("nvim" "vim" "tmux" "karabiner" "ideavim" "zsh" "git" "ssh" "gpg" "sketchybar")
fi

if [[ -z $DOTFILES ]]; then
	DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS
DOTFILES=$DOTFILES
