#!/usr/bin/env bash

# environment variables
if [[ -z $STOW_FOLDERS ]]; then
	STOW_FOLDERS=("alacritty" "firefox" "nvim" "tmux" "i3" "ideavim" "dunst" "bash" "zsh" "git")
fi

if [[ -z $DOTFILES ]]; then
	DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS
DOTFILES=$DOTFILES
