#!/usr/bin/env bash

# environment variables
if [[ -z $STOW_FOLDERS ]]; then
	# if using bash
	if [[ $SHELL = "/bin/bash" ]]; then
		STOW_FOLDERS=("nvim" "tmux" "i3" "dunst" "aliases" "bash" "zsh")
	else
		# if using zsh
		STOW_FOLDERS="nvim, tmux, i3, dunst, aliases, bash, zsh"
	fi
fi

if [[ -z $DOTFILES ]]; then
	DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS
DOTFILES=$DOTFILES
