#!/usr/bin/env bash

# environment variables
if [[ -z $STOW_FOLDERS ]]; then
	# STOW_FOLDERS="bin,i3,netflix,nvim,personal,tmux,uwuntu,xkb,zsh"
	STOW_FOLDERS=("nvim" "tmux" "i3")
fi

if [[ -z $DOTFILES ]]; then
	DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS
DOTFILES=$DOTFILES
