-- local status, copilot = pcall(require, 'copilot')
-- if not status then
--     return
-- end
-- -- vim.cmd([[imap <silent><script><expr> <C-L> copilot#Accept("\<CR>")]])
-- copilot.setup({
--     suggestion = { enabled = false },
--     panel = { enabled = false },
--     filetypes = {
--         ['*'] = true,
--         gitcommit = false,
--         NeogitCommitMessage = false,
--         NvimTree = false,
--     },
--     auto_refresh = true,
-- })
